### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by faraperu** [simongraham/dsf-cnn#3]
i get the following error, may i know how to fix it?
![error](https://user-images.githubusercontent.com/34961521/86432974-fcc16e80-bd2b-11ea-96a2-36d6cbc79bf5.PNG)

**Comment by simongraham** [comment]
Thanks for spotting this- I will make a fix to the repo over the next couple of days and will notify on here :)

**Comment by faraperu** [comment]
Oh thank you very much for your reply, every day i have been checking to see if you replied. Now am confident.

**Comment by simongraham** [comment]
This has now been fixed in [this commit](https://github.com/simongraham/dsf-cnn/commit/e81288384a9b99a59b8bcc2f58237513f028a935). Thanks for pointing it out.

**Comment by faraperu** [comment]
you are most well. Thanks too for this great work and most importantly for sharing

**Comment by faraperu** [comment]
Dear Mr. Simon,
I still get the following assertion error message.

>

**Comment by simongraham** [comment]
Hi @faraperu , 

I think you forgot to include the assertion message. I tested the code to ensure that it works when I made the recent change. Please check to make sure that you are using the same libraries. You can set up the environment as is mentioned on the README.

**Comment by faraperu** [comment]
Hi Simon,
I reimplemented according to your specifications however the system aborted
the execution  saying that the tensorflow library was compiled to use AVX
instructions , but these are not available on my machine. yet am using
intel pentium cpu G3260. UBUNTU 16.04 LTS.
